name        : loopbreaker
synopsis    : inline self-recursive definitions
description : Please see the README file
version     : 0.1.0.0
category    : Plugin
github      : "polysemy-research/loopbreaker"
license     : BSD3
author      : ["Matej Nižník", "Sandy Maguire"]
maintainer  : "matten@tuta.io"
copyright   : ["2019 Matej Nižník", "2019 Sandy Maguire"]

extra-source-files : [README.md, ChangeLog.md]

dependencies :
- base             >= 4.7     && < 5
- ghc              >= 8.6     && < 8.7
- syb              >= 0.7     && < 0.8
- containers       >= 0.6.0.1 && < 0.7

library :
  source-dirs     : src
  exposed-modules : [Loopbreaker.Plugin]

tests :
  loopbreaker-test :
    main         : Spec.hs
    source-dirs  : test
    ghc-options  :
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Loopbreaker.Plugin
    build-tools  :
    - hspec-discover
    dependencies :
    - loopbreaker
    - hspec              >= 2.6.1   && < 3
    - inspection-testing >= 0.4.2.1 && < 0.5

ghc-options :
- -Wall

default-extensions :
- ConstraintKinds
- FlexibleContexts
- KindSignatures
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- TupleSections
- TypeFamilies
- UnicodeSyntax
- ViewPatterns
